### ISSUE TITLE
Hijri Date lib is a 3rd party lib and is included incorrectly.

### ISSUE THREAD

**Issue by danmarsden** [eummena/moodle-calendartype_ummulqora#2]
when including a 3rd party lib file, you shouldn't add the Moodle gpl header to it - especially when the file has it's own license listed.

you also need to add a "thirdpartylibs.xml" file to the root of the repository that names the file and what license it uses - for more info see:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

**Comment by azmatksa** [comment]
Dear @danmarsden ,

We've updated the latest version of plugin in community and in plugin we added "thirdpartylibs.xml" as per the structue.

Thank you.
